name: responsive_layout_grid
description: The ResponsiveLayoutGrid provides a convenient responsive layout structure for elements within the body region.
version: 1.1.1
repository: https://github.com/domain-centric/responsive_layout_grid
documentation: https://github.com/domain-centric/responsive_layout_grid/wiki

environment:
  sdk: '^3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.3
  documentation_builder: ^0.0.14

flutter:
  uses-material-design: true
  module:
    androidX: true
    androidPackage: com.example.responsive_layout_grid
    iosBundleIdentifier: com.example.responsiveLayoutGrid
