name: responsive_layout_grid
description: The ResponsiveLayoutGrid provides a convenient responsive layout structure for elements within the body region.
version: 1.1.0
repository: https://github.com/domain-centric/responsive_layout_grid
documentation: https://github.com/domain-centric/responsive_layout_grid/wiki

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  documentation_builder: ^0.0.11

flutter:
  uses-material-design: true
  module:
    androidX: true
    androidPackage: com.example.responsive_layout_grid
    iosBundleIdentifier: com.example.responsiveLayoutGrid
